apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: deivi-motors-db
  namespace: deivi-motors-k8s
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore

  target:
    name: deivi-motors-db-secret
    creationPolicy: Owner
  data:
    - secretKey: MONGODB_USERNAME
      remoteRef:
        key: "${SECRET_NAME}"
        property: MONGODB_USERNAME

    - secretKey: MONGODB_PASSWORD
      remoteRef:
        key: "${SECRET_NAME}"
        property: MONGODB_PASSWORD
