apiVersion: v1
kind: ServiceAccount
metadata:
  name: deivi-motors-sa
  namespace: deivi-motors-k8s
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::404234478011:role/deivi-motors-irsa-role #Adicionar o Id da conta